import type { IncidentRecord } from './storage'

/**
 * Export helpers for the private incident record.
 *
 * The export is a plain text file created entirely on this device and
 * downloaded via the browser — nothing is uploaded or sent anywhere.
 */

/** YYYY-MM-DD → DD-MM-YYYY for display/export. */
export function formatDate(iso: string): string {
  const [y, m, d] = iso.split('-')
  return y && m && d ? `${d}-${m}-${y}` : iso
}

function line(label: string, value: string): string {
  return value.trim() ? `${label}: ${value.trim()}` : `${label}: —`
}

/** Build the human-readable incident record document. */
export function buildIncidentRecordText(r: IncidentRecord): string {
  const now = new Date()
  const exportedOn = `${now.getDate()}-${String(now.getMonth() + 1).padStart(2, '0')}-${now.getFullYear()}`

  const parts: string[] = []
  parts.push('NYAYANOW')
  parts.push('PRIVATE INCIDENT RECORD')
  parts.push('='.repeat(28))
  parts.push('')
  parts.push(line('Incident date', r.date ? formatDate(r.date) : ''))
  parts.push(line('Incident time', r.time))
  parts.push(line('Incident location', r.location))
  parts.push(line('Police station', r.station))
  parts.push(line('Officer details', r.officer))
  if (r.what.trim()) {
    parts.push('')
    parts.push('What happened:')
    parts.push(r.what.trim())
  }

  if (r.events.length > 0) {
    parts.push('')
    parts.push('TIMELINE')
    parts.push('-'.repeat(28))
    r.events.forEach((ev, i) => {
      const when = [ev.date ? formatDate(ev.date) : '', ev.time].filter(Boolean).join(', ')
      parts.push('')
      parts.push(`Event ${i + 1}${when ? ` — ${when}` : ''}`)
      if (ev.title.trim()) parts.push(`Title: ${ev.title.trim()}`)
      if (ev.description.trim()) parts.push(`Description: ${ev.description.trim()}`)
      if (ev.location.trim()) parts.push(`Location: ${ev.location.trim()}`)
      if (ev.notes.trim()) parts.push(`Notes: ${ev.notes.trim()}`)
    })
  }

  if (r.notes.trim()) {
    parts.push('')
    parts.push('Notes:')
    parts.push(r.notes.trim())
  }

  parts.push('')
  parts.push('-'.repeat(28))
  parts.push(`Generated by NyayaNow on ${exportedOn}.`)
  parts.push('Keep this file somewhere secure.')
  parts.push('Cached information — verify against official sources.')

  return parts.join('\n')
}

/** Download a text file entirely on-device (works offline). */
export function downloadTextFile(filename: string, text: string): void {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
