import { classify } from './classifier'
import type { SituationId } from '../data/types'
import type { UIKey } from '../data/ui'
import { getAIConfig } from './aiConfig'

/**
 * NyayaNow Situation Navigator — understanding layer.
 *
 * ARCHITECTURE (product rule): understanding is SEPARATE from legal truth.
 * This module only answers "what situation is this person describing?". It
 * NEVER generates legal rights, advice, sections or sources. Once a situation
 * is identified, the verified knowledge base (situations.ts / sources.ts) is
 * read for the actual guidance.
 *
 * LAYERED / HYBRID FLOW:
 *   1. safety scan (immediate danger → escalation, never ignored)
 *   2. arrest-uncertainty scan (→ Questioned vs Arrested decision tool)
 *   3. the existing local keyword classifier (fast, offline, private)
 *   4. structured context extraction (traffic, vehicle, phone, money, …)
 *   5. HIGH confidence → verified guide, no external call
 *   6. otherwise, IF the user opted in AND an AI proxy is configured:
 *      the LLM is asked ONLY to understand the situation (structured JSON,
 *      schema-validated). Legal guidance is never generated by the model.
 *   7. dynamic everyday-language clarification (max 3 questions, always an
 *      "I'm not sure" option) when routing is still ambiguous
 *   8. honest UNKNOWN fallback — we never guess about legal rights
 *
 * Nothing is faked: without a configured proxy the local engine IS the
 * understanding layer and the UI says so. AI failure always falls back to the
 * local result — the app never breaks.
 */

export type RouteSituationId = SituationId | 'TRAFFIC_UNVERIFIED'

export type Confidence = 'HIGH' | 'MEDIUM' | 'LOW'

export interface NavigatorContext {
  vehicleInvolved?: boolean
  vehicleType?: string
  documentsRequested?: boolean
  questioning?: boolean
  searchInvolved?: boolean
  propertyInvolved?: boolean
  phoneInvolved?: boolean
  moneyRequested?: boolean
  arrestMentioned?: boolean
  harmMentioned?: boolean
  trafficMentioned?: boolean
  challanMentioned?: boolean
  unableToLeave?: boolean
  locationContext?: string
}

export interface ClarificationOption {
  id: string
  /** UI label key (labels live in ui.ts so localization stays in one place). */
  labelKey: UIKey
  /** Picking this resolves to a verified situation (or the honest fallback). */
  situationId?: RouteSituationId
  /** Picking this advances to another clarification step. */
  nextStepId?: string
  /** Picking this is itself a safety signal (e.g. "threatening or hurting me"). */
  safetySignal?: boolean
  /** Picking this routes to the Questioned-vs-Arrested decision tool. */
  uncertaintySignal?: boolean
  /** "I'm not sure" — the option exists so the user is never stuck. */
  unsure?: boolean
}

export interface ClarificationStep {
  id: string
  /** Asked in everyday language — the user never needs a legal term. */
  questionKey: UIKey
  /** "We ask this because…" — a subtle trust-building explanation. */
  whyKey: UIKey
  options: ClarificationOption[]
}

export interface Clarification {
  steps: ClarificationStep[]
  currentStepId: string
}

export interface SituationUnderstanding {
  situationId: RouteSituationId
  confidence: Confidence
  context: NavigatorContext
  needsClarification: boolean
  clarification?: Clarification
  /** Immediate danger detected — the UI must show the safety card first. */
  safetyConcern: boolean
  /** "Questioned or arrested?" — the UI routes to the decision tool. */
  arrestUncertainty: boolean
  matchedTerms: string[]
}

export interface SituationUnderstandingProvider {
  name: 'local' | 'hybrid'
  /** Honest disclosure shown in the UI (where the description is processed). */
  processingNoteKey: UIKey
  /** Whether an external AI service is configured for this build. */
  aiAssistAvailable: boolean
  /** Whether the user has opted in to AI assist (default: off). */
  aiAssistEnabled: boolean
  setAiAssistEnabled: (on: boolean) => void
  analyze: (userText: string) => Promise<SituationUnderstanding>
  resolveClarification: (stepId: string, optionId: string) => SituationUnderstanding
}

/* ────────────────────────────────────────────────────────────────
   Context keywords (English + Hindi + Telugu). These only set flags —
   they never produce legal content.
──────────────────────────────────────────────────────────────── */

const KW = {
  vehicle: [
    'bike', 'scooter', 'motorcycle', 'two-wheeler', 'car', 'vehicle', 'driving',
    'drive', 'drove', 'riding', 'ride', 'traffic', 'road', 'highway',
    'गाड़ी', 'बाइक', 'कार', 'वाहन', 'ड्राइव', 'स्कूटर',
    'బైక్', 'కారు', 'వాహనం', 'డ్రైవింగ్', 'స్కూటర్'
  ],
  challan: [
    'challan', 'fine', 'fined', 'penalty', 'चालान', 'जुर्माना', 'చలాన్', 'జరిమానా'
  ],
  documents: [
    'licence', 'license', 'rc', 'registration', 'documents', 'papers',
    'दस्तावेज़', 'दस्तावेज', 'लाइसेंस', 'లైసెన్స్', 'పత్రాలు', 'రిజిస్ట్రేషన్'
  ],
  phone: [
    'phone', 'mobile', 'smartphone', 'फोन', 'फ़ोन', 'मोबाइल', 'ఫోన్', 'మొబైల్'
  ],
  money: [
    'money', 'cash', 'पैसे', 'पैसा', 'रुपये', 'డబ్బు', 'నగదు'
  ],
  search: [
    'search', 'searching', 'frisk', 'check my', 'checking my', 'look through', 'go through',
    'तलाशी', 'తలచి', 'సోదా', 'బ్యాగ్ చూడాలని', 'బ్యాగ్ చూడాలి'
  ],
  questioning: [
    'asked me questions', 'asking me questions', 'asking questions', 'questioned me',
    'asked questions', 'questions', 'questioning', 'प्रश्न', 'पूछताछ', 'ప్రశ్నలు', 'ప్రశ్నిస్తున్నారు'
  ],
  station: ['station', 'थाने', 'थाना', 'స్టేషన్'],
  propertyTaken: [
    'took', 'taken', 'seized', 'seizure', 'confiscat', 'impound', 'keep my',
    'ज़ब्त', 'जब्त', 'ले लिया', 'తీసుకున్నారు', 'జప్తు'
  ],
  stopWords: ['stopped', 'stop me', 'रोका', 'रोक लिया', 'ఆపారు'],
  arrestWords: ['arrest', 'custody', 'गिरफ्तार', 'गिरफ़्तार', 'हिरासत', 'అరెస్ట్', 'కస్టడీ'],
  harmWords: [
    'threaten', 'threatened', 'threatening', 'abuse', 'abused', 'assault',
    'beaten', 'beat', 'slapped', 'hit', 'harass', 'harassed', 'torture',
    'धमकाया', 'धमका', 'मारा', 'पीटा', 'गाली', 'పిరికి', 'బెదిరించారు', 'కొట్టారు', 'వేధింపు'
  ]
} as const

/**
 * Immediate-danger phrases. These are deliberately narrow: ongoing violence,
 * threats to life or explicit danger. "Threatened me" (past, no life threat)
 * is NOT here — it routes to the verified abuse guide instead.
 */
const SAFETY_PHRASES = [
  'beating me', 'beating him', 'beating her', 'are beating', 'being beaten',
  'assaulting me', 'attacking me', 'hit me', 'hitting me', 'slapped me',
  'slapping me', 'threatened to kill', 'threaten to kill', 'threatens to kill',
  'killing me', 'will kill me', 'trying to kill', 'threatening to kill',
  'in immediate danger', 'immediate danger', 'danger right now', 'hurt me', 'hurting me',
  'मार रहे', 'पीट रहे', 'जान से मारने', 'जान से मार देंगे', 'धमका रहे',
  'చంపేస్తామని', 'చంపుతామని', 'కొడుతున్నారు', 'దాడి చేస్తున్నారు',
  'వెంటనే ప్రమాదం', 'ప్రమాదంలో ఉన్నాను'
]

/** "I don't know if I am arrested" — always routed to the decision tool. */
const ARREST_DOUBT_PHRASES = [
  "don't know if i am arrested", 'do not know if i am arrested', 'not sure if i am arrested',
  "don't know whether i am arrested", 'not sure whether i am arrested',
  'am i arrested', 'am i under arrest',
  'क्या मैं गिरफ्तार', 'क्या मुझे गिरफ्तार', 'पता नहीं गिरफ्तार',
  'నేను అరెస్ట్ అయ్యానా', 'అరెస్ట్ అయ్యానా తెలియదు'
]

/**
 * Detention-like signals described in ordinary words ("told to come with
 * them", "won't let me leave"). We NEVER declare an arrest — these route to
 * the Questioned-vs-Arrested decision tool, which explains that the rules
 * depend on the circumstances.
 */
const DETENTION_PHRASES = [
  "won't let me leave", 'wont let me leave', 'not letting me leave', "can't leave",
  'cannot leave', 'not allowed to leave', "won't allow me to leave", 'let me go',
  'took me with them', 'taking me with them', 'took me with him', 'told me to come with them',
  'told me to come with him', 'told me to come with her', 'asked me to come with them',
  'come with them', 'come with him', 'come with her', 'come with us', 'told me to come along',
  'put me in their vehicle', 'put me in their car', 'put me in their van', 'put me in their jeep',
  'जाने नहीं दे रहे', 'जाने नहीं दे रही', 'साथ चलने को कहा', 'मेरे साथ चलो',
  'अपने साथ ले गए', 'गाड़ी में बैठाया',
  'వెళ్లనివ్వడం లేదు', 'వెళ్లనివ్వట్లేదు', 'నాతో రమ్మన్నారు', 'వాళ్లతో రమ్మన్నారు',
  'తమ వాహనంలో ఎక్కించారు'
]

/** "I don't know what applies" — the honest fallback, never a guess. */
const UNSURE_PHRASES = [
  "don't know what", 'do not know what', 'not sure what', 'complicated',
  'मुझे नहीं पता', 'पता नहीं क्या', 'నాకు తెలియదు', 'తెలియదు ఏమి'
]

/* ────────────────────────────────────────────────────────────────
   Dynamic clarification — one everyday-language question at a time
   (maximum 3), about observable events. The user never needs a legal
   term, and every step has an "I'm not sure" option.
──────────────────────────────────────────────────────────────── */

const STEP_WHERE: ClarificationStep = {
  id: 'where',
  questionKey: 'anQWhere',
  whyKey: 'anQWhereWhy',
  options: [
    { id: 'road', labelKey: 'anOptOnRoad', nextStepId: 'what' },
    { id: 'home', labelKey: 'anOptAtHome', nextStepId: 'atHome' },
    { id: 'station', labelKey: 'anOptAtStation', nextStepId: 'atStation' },
    { id: 'elsewhere', labelKey: 'anOptElsewhere', nextStepId: 'what' },
    { id: 'whereUnsure', labelKey: 'anOptNotSure', nextStepId: 'what', unsure: true }
  ]
}

const STEP_WHAT: ClarificationStep = {
  id: 'what',
  questionKey: 'anQWhat',
  whyKey: 'anQWhatWhy',
  options: [
    { id: 'askedDocs', labelKey: 'anOptAskedDocs', situationId: 'POLICE_QUESTIONING' },
    { id: 'questions', labelKey: 'anOptQuestions', situationId: 'POLICE_QUESTIONING' },
    { id: 'checkThings', labelKey: 'anOptCheckThings', situationId: 'SEARCH' },
    { id: 'tookSomething', labelKey: 'anOptTookSomething', situationId: 'PROPERTY_SEIZED' },
    { id: 'money', labelKey: 'anOptMoney', situationId: 'BRIBE' },
    { id: 'comeWith', labelKey: 'anOptComeWith', uncertaintySignal: true },
    { id: 'wontLetLeave', labelKey: 'anOptWontLetLeave', uncertaintySignal: true },
    { id: 'harm', labelKey: 'anOptHarm', safetySignal: true },
    { id: 'whatUnsure', labelKey: 'anOptNotSure', nextStepId: 'took', unsure: true }
  ]
}

const STEP_TOOK: ClarificationStep = {
  id: 'took',
  questionKey: 'anQTook',
  whyKey: 'anQTookWhy',
  options: [
    { id: 'tookYes', labelKey: 'anOptTookYes', situationId: 'PROPERTY_SEIZED' },
    { id: 'checked', labelKey: 'anOptChecked', situationId: 'SEARCH' },
    { id: 'onlyTalked', labelKey: 'anOptOnlyTalked', situationId: 'POLICE_QUESTIONING' },
    { id: 'tookUnsure', labelKey: 'anOptNotSure', situationId: 'UNKNOWN', unsure: true }
  ]
}

const STEP_AT_HOME: ClarificationStep = {
  id: 'atHome',
  questionKey: 'anQAtHome',
  whyKey: 'anQAtHomeWhy',
  options: [
    { id: 'policeCameHome', labelKey: 'anOptPoliceCameHome', situationId: 'POLICE_AT_HOME' },
    { id: 'lookInside', labelKey: 'anOptLookInside', situationId: 'SEARCH' },
    { id: 'money', labelKey: 'anOptMoney', situationId: 'BRIBE' },
    { id: 'harm', labelKey: 'anOptHarm', safetySignal: true },
    { id: 'homeUnsure', labelKey: 'anOptNotSure', situationId: 'UNKNOWN', unsure: true }
  ]
}

const STEP_AT_STATION: ClarificationStep = {
  id: 'atStation',
  questionKey: 'anQAtStation',
  whyKey: 'anQAtStationWhy',
  options: [
    { id: 'askingQuestions', labelKey: 'anOptQuestions', situationId: 'POLICE_QUESTIONING' },
    { id: 'toldArrest', labelKey: 'anOptToldArrest', situationId: 'ARREST' },
    { id: 'wontLetLeave', labelKey: 'anOptWontLetLeave', uncertaintySignal: true },
    { id: 'firRefused', labelKey: 'anOptFir', situationId: 'FIR_REFUSED' },
    { id: 'harm', labelKey: 'anOptHarm', safetySignal: true },
    { id: 'stationUnsure', labelKey: 'anOptNotSure', situationId: 'UNKNOWN', unsure: true }
  ]
}

const STEPS: Record<string, ClarificationStep> = {
  where: STEP_WHERE,
  what: STEP_WHAT,
  took: STEP_TOOK,
  atHome: STEP_AT_HOME,
  atStation: STEP_AT_STATION
}

const ALL_STEPS: ClarificationStep[] = [STEP_WHERE, STEP_WHAT, STEP_TOOK, STEP_AT_HOME, STEP_AT_STATION]

/* ────────────────────────────────────────────────────────────────
   Related verified guides shown after a result ("This may also involve").
──────────────────────────────────────────────────────────────── */

const RELATED: Record<RouteSituationId, SituationId[]> = {
  POLICE_QUESTIONING: ['PROPERTY_SEIZED', 'ARREST', 'SEARCH'],
  ARREST: ['POLICE_QUESTIONING', 'PROLONGED_DETENTION', 'POLICE_ABUSE'],
  FIR_REFUSED: ['COMPLAINT', 'POLICE_REFUSED_HELP'],
  SEARCH: ['PROPERTY_SEIZED', 'WOMEN_AND_POLICE', 'POLICE_QUESTIONING'],
  PROPERTY_SEIZED: ['SEARCH', 'BRIBE', 'POLICE_QUESTIONING'],
  POLICE_ABUSE: ['COMPLAINT', 'ARREST', 'BRIBE'],
  BRIBE: ['COMPLAINT', 'POLICE_ABUSE', 'POLICE_QUESTIONING'],
  COMPLAINT: ['FIR_REFUSED', 'POLICE_REFUSED_HELP'],
  WOMEN_AND_POLICE: ['SEARCH', 'POLICE_ABUSE'],
  PROLONGED_DETENTION: ['ARREST', 'POLICE_ABUSE'],
  POLICE_REFUSED_HELP: ['FIR_REFUSED', 'COMPLAINT'],
  POLICE_NOTICE: ['POLICE_QUESTIONING', 'ARREST'],
  POLICE_AT_HOME: ['SEARCH', 'POLICE_QUESTIONING'],
  NOT_SURE: [],
  UNKNOWN: [],
  TRAFFIC_UNVERIFIED: ['POLICE_QUESTIONING', 'PROPERTY_SEIZED', 'SEARCH']
}

export function getRelatedSituations(id: RouteSituationId): SituationId[] {
  return RELATED[id] ?? []
}

/* ────────────────────────────────────────────────────────────────
   Local engine (fully on-device, deterministic, private)
──────────────────────────────────────────────────────────────── */

function hasAny(text: string, terms: readonly string[]): boolean {
  return terms.some((term) => text.includes(term))
}

/** True when the description carries a signal beyond a bare "stopped me". */
function hasContextBeyondStop(ctx: NavigatorContext): boolean {
  return Boolean(
    ctx.documentsRequested ||
      ctx.questioning ||
      ctx.searchInvolved ||
      ctx.propertyInvolved ||
      ctx.phoneInvolved ||
      ctx.moneyRequested ||
      ctx.harmMentioned ||
      ctx.arrestMentioned ||
      ctx.trafficMentioned ||
      ctx.challanMentioned
  )
}

function detectVehicleType(text: string): string | undefined {
  if (/(bike|scooter|motorcycle|two-wheeler|बाइक|स्कूटर|బైక్|స్కూటర్)/.test(text)) return 'two-wheeler'
  if (/(car|four-wheeler|गाड़ी|कार|కారు)/.test(text)) return 'car'
  if (/(vehicle|वाहन|వాహనం)/.test(text)) return 'other'
  return undefined
}

function buildContext(text: string): NavigatorContext {
  return {
    vehicleInvolved: hasAny(text, KW.vehicle),
    vehicleType: detectVehicleType(text),
    documentsRequested: hasAny(text, KW.documents),
    questioning: hasAny(text, KW.questioning) || hasAny(text, KW.station),
    searchInvolved: hasAny(text, KW.search),
    propertyInvolved: hasAny(text, KW.propertyTaken),
    phoneInvolved: hasAny(text, KW.phone),
    moneyRequested: hasAny(text, KW.money),
    arrestMentioned: hasAny(text, KW.arrestWords),
    harmMentioned: hasAny(text, KW.harmWords),
    trafficMentioned: hasAny(text, KW.vehicle) || hasAny(text, KW.challan),
    challanMentioned: hasAny(text, KW.challan),
    unableToLeave: hasAny(text, DETENTION_PHRASES)
  }
}

/** Local-classifier confidence is a number 0–1; HIGH needs a clear winner. */
const HIGH_CONFIDENCE = 0.72

/** A clarification-focused understanding for a given step (or the first step). */
export function getClarification(
  stepId: string,
  context: NavigatorContext = {},
  safetyConcern = false,
  arrestUncertainty = false,
  matchedTerms: string[] = []
): SituationUnderstanding {
  const currentStepId = STEPS[stepId] ? stepId : 'where'
  return {
    situationId: 'UNKNOWN',
    confidence: 'LOW',
    context,
    needsClarification: true,
    clarification: { steps: ALL_STEPS, currentStepId },
    safetyConcern,
    arrestUncertainty,
    matchedTerms
  }
}

export function analyzeLocal(text: string): SituationUnderstanding {
  const lower = text.toLowerCase().trim()
  const context = buildContext(lower)

  const safetyConcern = hasAny(lower, SAFETY_PHRASES)
  const arrestUncertainty = hasAny(lower, ARREST_DOUBT_PHRASES) || hasAny(lower, DETENTION_PHRASES)

  const classified = classify(text)
  const highConf = classified.situationId !== 'UNKNOWN' && classified.confidence >= HIGH_CONFIDENCE

  const base = (patch: Partial<SituationUnderstanding>): SituationUnderstanding => ({
    situationId: 'UNKNOWN',
    confidence: 'LOW',
    context,
    needsClarification: false,
    safetyConcern,
    arrestUncertainty,
    matchedTerms: classified.matchedTerms,
    ...patch
  })

  // 1. Immediate danger — safety card comes first, always.
  if (safetyConcern) {
    return base({ situationId: 'POLICE_ABUSE', confidence: 'HIGH' })
  }

  // 2. "I don't know if I am arrested" / "told to come with them" — we never
  //    decide an arrest for the user; the decision tool does.
  if (arrestUncertainty) {
    return base({ situationId: 'UNKNOWN', confidence: 'LOW' })
  }

  // 2b. A bare "police stopped me" is genuinely ambiguous (documents? search?
  //     money? arrest?) — start the guided everyday-language flow instead of
  //     guessing which guide fits. With any real signal we go straight to the
  //     verified guide.
  const bareStop =
    classified.situationId === 'POLICE_QUESTIONING' &&
    hasAny(lower, KW.stopWords) &&
    !hasContextBeyondStop(context)
  if (bareStop) {
    return getClarification('where', context, safetyConcern, arrestUncertainty, classified.matchedTerms)
  }

  // 3. High-confidence local classification → verified guide directly.
  if (highConf) {
    return base({ situationId: classified.situationId, confidence: 'HIGH' })
  }

  // 4. Any real classifier match (score ≥ 3) → verified guide, MEDIUM.
  if (classified.situationId !== 'UNKNOWN' && classified.confidence >= 0.6) {
    return base({ situationId: classified.situationId, confidence: 'MEDIUM' })
  }

  // 5. "I don't know what applies" → honest fallback, never a guess.
  if (hasAny(lower, UNSURE_PHRASES)) {
    return base({ situationId: 'UNKNOWN', confidence: 'LOW' })
  }

  // 6. Structured context routing (no classifier match). Traffic is handled
  //    honestly: challan/fine law is NOT in the verified KB yet, so we never
  //    invent Motor Vehicles Act guidance.
  if (context.challanMentioned) {
    return base({ situationId: 'TRAFFIC_UNVERIFIED', confidence: 'MEDIUM' })
  }
  if (context.searchInvolved) return base({ situationId: 'SEARCH', confidence: 'MEDIUM' })
  if ((context.vehicleInvolved || context.phoneInvolved || context.documentsRequested) && context.propertyInvolved) {
    return base({ situationId: 'PROPERTY_SEIZED', confidence: 'MEDIUM' })
  }
  if (context.propertyInvolved) return base({ situationId: 'PROPERTY_SEIZED', confidence: 'MEDIUM' })
  if (context.questioning || context.documentsRequested) {
    return base({ situationId: 'POLICE_QUESTIONING', confidence: 'MEDIUM' })
  }
  if (context.trafficMentioned && (context.vehicleInvolved || hasAny(lower, KW.stopWords))) {
    return base({ situationId: 'POLICE_QUESTIONING', confidence: 'MEDIUM' })
  }
  if (context.moneyRequested) return base({ situationId: 'BRIBE', confidence: 'MEDIUM' })
  if (context.harmMentioned) return base({ situationId: 'POLICE_ABUSE', confidence: 'MEDIUM' })
  if (context.arrestMentioned) return base({ situationId: 'ARREST', confidence: 'MEDIUM' })
  if (context.trafficMentioned) {
    return base({ situationId: 'TRAFFIC_UNVERIFIED', confidence: 'MEDIUM' })
  }

  // 7. Nothing matched → dynamic everyday-language clarification, then fall
  //    back safely. Never a guess about legal rights.
  return getClarification('where', context, safetyConcern, arrestUncertainty, classified.matchedTerms)
}

/** Resolve one clarification option (terminal situation, safety, or next step). */
export function resolveClarificationStep(stepId: string, optionId: string): SituationUnderstanding {
  const step = STEPS[stepId]
  const option = step?.options.find((o) => o.id === optionId)
  if (!option) {
    return {
      situationId: 'UNKNOWN',
      confidence: 'LOW',
      context: {},
      needsClarification: false,
      safetyConcern: false,
      arrestUncertainty: false,
      matchedTerms: []
    }
  }
  if (option.safetySignal) {
    return {
      situationId: 'POLICE_ABUSE',
      confidence: 'HIGH',
      context: {},
      needsClarification: false,
      safetyConcern: true,
      arrestUncertainty: false,
      matchedTerms: []
    }
  }
  if (option.uncertaintySignal) {
    return {
      situationId: 'UNKNOWN',
      confidence: 'LOW',
      context: {},
      needsClarification: false,
      safetyConcern: false,
      arrestUncertainty: true,
      matchedTerms: []
    }
  }
  if (option.situationId) {
    return {
      situationId: option.situationId,
      confidence: 'MEDIUM',
      context: {},
      needsClarification: false,
      safetyConcern: false,
      arrestUncertainty: false,
      matchedTerms: []
    }
  }
  if (option.nextStepId) {
    return getClarification(option.nextStepId)
  }
  return getClarification('where')
}

/* ────────────────────────────────────────────────────────────────
   LLM provider (optional) — situation understanding ONLY.
   Structured JSON is validated before use; anything invalid fails
   closed and the hybrid falls back to the local engine.
──────────────────────────────────────────────────────────────── */

const AI_ALLOWED_IDS = new Set<string>([
  'POLICE_QUESTIONING', 'ARREST', 'FIR_REFUSED', 'SEARCH', 'PROPERTY_SEIZED',
  'POLICE_ABUSE', 'BRIBE', 'COMPLAINT', 'WOMEN_AND_POLICE', 'PROLONGED_DETENTION',
  'POLICE_REFUSED_HELP', 'POLICE_NOTICE', 'POLICE_AT_HOME', 'NOT_SURE', 'UNKNOWN',
  'TRAFFIC_UNVERIFIED', 'ARREST_UNCERTAIN'
])

const CONTEXT_KEYS = [
  'vehicleInvolved', 'documentsRequested', 'questioning', 'searchInvolved',
  'propertyInvolved', 'phoneInvolved', 'moneyRequested', 'arrestMentioned',
  'harmMentioned', 'trafficMentioned', 'challanMentioned', 'unableToLeave'
] as const

/** The ONLY shape the LLM is allowed to produce (after validation). */
export interface AISituationResult {
  situationId: string
  confidence: Confidence
  context: NavigatorContext
  needsClarification: boolean
  clarifyingQuestion?: string
}

/**
 * Strict schema validation for the model's structured output. Only the listed
 * fields are ever read — any legal content the model might emit is ignored.
 * Returns null when the output is unusable (caller falls back safely).
 */
export function validateAIResult(raw: unknown): AISituationResult | null {
  if (typeof raw !== 'object' || raw === null) return null
  const r = raw as Record<string, unknown>
  if (typeof r.situationId !== 'string' || !AI_ALLOWED_IDS.has(r.situationId)) return null
  if (r.confidence !== 'HIGH' && r.confidence !== 'MEDIUM' && r.confidence !== 'LOW') return null

  const context: NavigatorContext = {}
  if (typeof r.context === 'object' && r.context !== null) {
    const c = r.context as Record<string, unknown>
    for (const key of CONTEXT_KEYS) {
      if (typeof c[key] === 'boolean') context[key] = c[key] as boolean
    }
    if (typeof c.vehicleType === 'string') context.vehicleType = c.vehicleType
    if (typeof c.locationContext === 'string') context.locationContext = c.locationContext
  }

  return {
    situationId: r.situationId,
    confidence: r.confidence,
    context,
    needsClarification: r.needsClarification === true,
    clarifyingQuestion: typeof r.clarifyingQuestion === 'string' ? r.clarifyingQuestion : undefined
  }
}

export function aiResultToUnderstanding(valid: AISituationResult): SituationUnderstanding {
  const base: SituationUnderstanding = {
    situationId: 'UNKNOWN',
    confidence: valid.confidence,
    context: valid.context,
    needsClarification: false,
    safetyConcern: false,
    arrestUncertainty: false,
    matchedTerms: []
  }

  // ARREST_UNCERTAIN is not a verified page — the Questioned-vs-Arrested
  // decision tool explains that the rules depend on the circumstances.
  if (valid.situationId === 'ARREST_UNCERTAIN') {
    return { ...base, arrestUncertainty: true }
  }
  if (valid.needsClarification) {
    // We never render the model's own question text. Clarification goes
    // through the curated everyday-language flow (max 3 questions).
    return getClarification('where', valid.context)
  }
  if (valid.situationId === 'UNKNOWN' || valid.situationId === 'NOT_SURE') {
    return base
  }
  return { ...base, situationId: valid.situationId as RouteSituationId }
}

const AI_TIMEOUT_MS = 12_000

async function llmAnalyze(text: string): Promise<SituationUnderstanding | null> {
  const cfg = getAIConfig()
  if (!cfg.available || !cfg.endpoint) return null

  try {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), AI_TIMEOUT_MS)
    let res: Response
    try {
      res = await fetch(cfg.endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify({ text }),
        signal: controller.signal
      })
    } finally {
      clearTimeout(timer)
    }
    if (!res.ok) return null
    const data: unknown = await res.json().catch(() => null)
    const valid = validateAIResult(data)
    return valid ? aiResultToUnderstanding(valid) : null
  } catch {
    return null
  }
}

/* ────────────────────────────────────────────────────────────────
   Providers — local (always) and hybrid (local first, optional AI).
──────────────────────────────────────────────────────────────── */

export type LLMAnalyzer = (text: string) => Promise<SituationUnderstanding | null>

export function createHybridProvider(opts?: { llm?: LLMAnalyzer; available?: boolean }): SituationUnderstandingProvider {
  const llm = opts?.llm ?? llmAnalyze
  const available = opts?.available ?? getAIConfig().available
  let enabled = false

  return {
    name: 'hybrid',
    get processingNoteKey(): UIKey {
      if (!available) return 'anOnDevice'
      return enabled ? 'anAIAssistNote' : 'anPrivateModeNote'
    },
    get aiAssistAvailable() {
      return available
    },
    get aiAssistEnabled() {
      return enabled
    },
    setAiAssistEnabled(on: boolean) {
      enabled = on
    },
    async analyze(text: string): Promise<SituationUnderstanding> {
      const local = analyzeLocal(text)

      // Safety and arrest-uncertainty are never delegated to AI, and a
      // confident local match needs no network call (speed + privacy).
      if (local.safetyConcern || local.arrestUncertainty || local.confidence === 'HIGH') return local

      // MEDIUM / LOW / UNKNOWN → optional AI situation understanding.
      if (enabled && available) {
        const ai = await llm(text)
        if (ai) return ai
        // AI unavailable, rate-limited, invalid JSON or timeout → the local
        // result is used (verified guide, curated clarification, or honest
        // UNKNOWN). The app never breaks because of AI.
      }
      return local
    },
    resolveClarification: resolveClarificationStep
  }
}

/** The active provider — local first, AI assist only when configured + opted in. */
export const hybridSituationProvider = createHybridProvider()

/** Pure local provider (used by tests and as the honest baseline). */
export const localSituationProvider: SituationUnderstandingProvider = {
  name: 'local',
  processingNoteKey: 'anOnDevice',
  aiAssistAvailable: false,
  aiAssistEnabled: false,
  setAiAssistEnabled() {
    /* local provider has no external assist */
  },
  async analyze(text: string): Promise<SituationUnderstanding> {
    return analyzeLocal(text)
  },
  resolveClarification: resolveClarificationStep
}

export function getSituationProvider(): SituationUnderstandingProvider {
  return hybridSituationProvider
}
